Initial Setup of Node Project
Maosorio92/workshop-api-testing-js pull request #1
Opened 2022-06-21 03:34 UTC by Maosorio92

2022-06-21 03:36 UTC, danielgalvis98 commented on .github/CODEOWNERS
> +* @holgiosalos @danielgalvis98 @kliver98 @AlejaGonzalezV @NicolasB2 @manuelq12 @Valeryibarra @veronicatofino
Add End of File (EOF)

2022-06-21 03:37 UTC, danielgalvis98 commented on test/HelloWorld.test.js
> +});
Add EOF

2022-06-21 03:37 UTC, danielgalvis98 requested changes
Also add the description to the Readme

2022-06-21 13:32 UTC, NicolasB2 commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/windows,visualstudiocode,node
Add EOF

2022-06-22 01:08 UTC, Maosorio92 commented on .github/CODEOWNERS
> +* @holgiosalos @danielgalvis98 @kliver98 @AlejaGonzalezV @NicolasB2 @manuelq12 @Valeryibarra @veronicatofino
Thank you!

2022-06-22 01:46 UTC, Maosorio92 commented on test/HelloWorld.test.js
> +});
Ok

2022-06-22 01:46 UTC, Maosorio92 commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/windows,visualstudiocode,node
Ok, thank you

2022-06-22 03:17 UTC, danielgalvis98 requested changes

2022-06-22 03:17 UTC, danielgalvis98 commented on README.md
> +This is the first workshop about API testing by Manuel Osorio
Put this as the second line and with "##"
```suggestion
# workshop-api-testing-js
## This is the first workshop about API testing by Manuel Osorio
```

2022-06-22 04:25 UTC, danielgalvis98 commented on README.md
>  # workshop-api-testing-js
Remove this line

2022-06-22 13:16 UTC, Maosorio92 commented on README.md
>  # workshop-api-testing-js
Hello!
I have a question, yesterday, I accepted the first change you made in readme.md file, then, you suggested me to erase a line, but now, I don´t know how to accept this change, in fact, now I don´t see the line you suggested me to erase. I am confused.

2022-06-22 13:17 UTC, Maosorio92 commented on README.md
>  # workshop-api-testing-js
Or is it better for me tu push the file again?

2022-06-22 13:49 UTC, veronicatofino commented on README.md
>  # workshop-api-testing-js
@Maosorio92 The third line is the one to remove. You are repeating it from the first line.

2022-06-22 14:23 UTC, danielgalvis98 commented on README.md
>  # workshop-api-testing-js
@Maosorio92 As Veronica says, the line I'm referring to is the third line, that has `# workshop-api-testing-js` repeated.

2022-06-22 14:29 UTC, holgiosalos commented on package.json
> +  }
are these dependencies required? I think that just mocha and chai as dev dependencies are required for this step

2022-06-22 22:29 UTC, manuelq12 approved these changes

2022-06-23 23:37 UTC, danielgalvis98 approved these changes

2022-06-23 23:51 UTC, merged